# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TransformersTokenizer": "01_tokenizers.ipynb",
         "GPT2DecoderTokenizer": "01_tokenizers.ipynb",
         "TransformersNumericalize": "02_transforms.ipynb",
         "Pad2Max": "02_transforms.ipynb",
         "bert_SeqClassification_split": "03_model_splits.ipynb",
         "roberta_SeqClassification_split": "03_model_splits.ipynb",
         "gpt2_lmhead_split": "03_model_splits.ipynb",
         "distilbert_SeqClassification_split": "03_model_splits.ipynb",
         "albert_SeqClassification_split": "03_model_splits.ipynb",
         "GPT2LMHeadCallback": "04_callbacks.ipynb",
         "BertSeqClassificationCallback": "04_callbacks.ipynb",
         "GeneratedLM": "05_GeneratedLM.ipynb",
         "generate": "05_GeneratedLM.ipynb"}

modules = ["tokenizers.py",
           "transforms.py",
           "model_splits.py",
           "callbacks.py",
           "generated_lm.py"]

doc_url = "https://cwza.github.io/fastai_transformers_utils/"

git_url = "https://github.com/cwza/fastai_transformers_utils/tree/master/"

def custom_doc_links(name): return None
