# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TransformersTokenizer": "00_general.ipynb",
         "TransformersNumericalize": "00_general.ipynb",
         "Pad2Max": "00_general.ipynb",
         "bert_SeqClassification_split": "00_general.ipynb",
         "distilbert_SeqClassification_split": "00_general.ipynb",
         "albert_SeqClassification_split": "00_general.ipynb",
         "roberta_SeqClassification_split": "00_general.ipynb",
         "gpt2_lmhead_split": "00_general.ipynb",
         "GPT2LMHeadCallback": "00_general.ipynb",
         "BertSeqClassificationCallback": "00_general.ipynb"}

modules = ["general.py"]

doc_url = "https://cwza.github.io/fastai_transformers_utils/"

git_url = "https://github.com/cwza/fastai_transformers_utils/tree/master/"

def custom_doc_links(name): return None
