# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TransformersTokenizer": "00_general.ipynb",
         "TransformersNumericalize": "01a_transforms.ipynb",
         "Pad2Max": "01a_transforms.ipynb",
         "bert_SeqClassification_split": "01b_model_splits.ipynb",
         "roberta_SeqClassification_split": "01b_model_splits.ipynb",
         "gpt2_lmhead_split": "01b_model_splits.ipynb",
         "distilbert_SeqClassification_split": "01b_model_splits.ipynb",
         "albert_SeqClassification_split": "01b_model_splits.ipynb",
         "GPT2LMHeadCallback": "01c_callbacks.ipynb",
         "BertSeqClassificationCallback": "01c_callbacks.ipynb"}

modules = ["general.py",
           "transforms.py",
           "model_splits.py",
           "callbacks.py"]

doc_url = "https://cwza.github.io/fastai_transformers_utils/"

git_url = "https://github.com/cwza/fastai_transformers_utils/tree/master/"

def custom_doc_links(name): return None
