# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_general.ipynb (unless otherwise specified).

__all__ = ['TransformersTokenizer']

# Cell
#export
from typing import *
from fastcore.all import *
from fastai2.basics import *

from transformers import PreTrainedTokenizer, AutoTokenizer

# Cell
class TransformersTokenizer():
    ''' fastai want the tokenizer can handle list of string.
        use in parallel_gen() '''
    def __init__(self, tokenizer: PreTrainedTokenizer):
        self.tokenizer = tokenizer
    def __call__(self, items: List[str]):
        return map(self.tokenizer.tokenize, items)